name: Update Coinfolio Data

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # כאן הוספנו לרובוט את כלי הסריקה לאתרים אחרים
        run: pip install yfinance pytz requests beautifulsoup4

      - name: Run update script
        run: python update_prices.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # כאן אנחנו אומרים לו לשמור את כל 3 הקבצים!
          git add prices.json index.html price_history.csv
          git commit -m "Update prices and database [skip ci]" || exit 0
          git push
