name: Update Coinfolio Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # הוספנו כאן את ספריית pytz לחישוב שעון ישראל
        run: pip install yfinance pytz

      - name: Run update script
        run: python update_prices.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # הוספנו כאן הוראה לשמור גם את קובץ ה-index.html
          git add prices.json index.html
          git commit -m "Update prices and HTML [skip ci]" || exit 0
          git push
